### ISSUE TITLE
[$300] Drone Series- Position update via SerialNumber not mongoId

### ISSUE THREAD

**Issue by kbowerma** [topcoderinc/dsp-server#171]
![](https://scontent.ford1-1.fna.fbcdn.net/v/t1.0-9/14717161_10154488333556101_5487997839680388224_n.png?oh=fd410a07763a52f126ae17433dc85340&oe=58A1F9EB)

We are super excited in how our drone series has been shaping up, the participation in this project has been incredible.   In two weeks we will be demoing the work we have done so far, so we have some loose ends we still need to tie up but we feel really good in what we have to show.  This challenge should be pretty quick so we are going to make it a First to finish and you should see a couple more just like it in the next 48 hours that are focused specifically on the drone position updates.    For this challenge (**Please pull from the dev branch**) we want to clone the service that updates the drones position   {{URL}}/drone/:id  and create a new service that does the exact same things but instead of taking in the id we want to pass the serial number.     We are not going to put a unique constraint on the database yet so you will have to select and update the first match you get on the serial number field.    Make the new PUT endpoint {{URL}}/drone/position/:SerialNumber.   It should support all the other Smart Location Updates described in the readme.  

We have to craft this PUT call on some [lower level MCUs](https://github.com/kbowerma/droneTracker) so we want to not be tied to the database.  If we need to move thing around we don't want to have to recompile our mcu (and raspberry pi) firmware.

Submission guidelines

1.  Be sure to start from the ```dev``` branch
2.  Zip your code into a single file and include the .git file.  ( It would be prefered to do a  local commit before you submit.)
3.  You should not touch the existing PUT update since we still want that.  
4.  Provide a postman collection or curl sample that shows your update via 

## Project Background

For this series we are creating a Drone Service Platform (DSP) which consist of  a marketplace where customers can request  drone services for providers/operators. Examples of the services would be drone delivery, mapping, monitoring and many other tasks. In addition to delivering drone services we will also provide a level of traffic management. 

# Links
[front end src: topcoderinc/dsp-frontend](http://github.com/topcoderinc/dsp-frontend)
[back end src: topcoderinc/dsp-server](http://github.com/topcoderinc/dsp-server)
[Live Heroku Dev Frontend:  http://kb-dsp-server-dev.herokuapp.com/api/v1](http://kb-dsp-server-dev.herokuapp.com/api-docs/)

**Comment by kbowerma** [comment]
Challenge created successfully
Challenge Url: https://www.topcoder.com/challenge-details/30056151/?type=develop&noncache=true

**Comment by muzehyun** [comment]
I think /drones/{id} is not working

{
  "error": "\"serialNumber\" is required",
  "status": 400
}

**Comment by n10l** [comment]
Yes, existing url is broken.

**Comment by billsedison** [comment]
Oh, yes, it is my fault due to a typo. I'm sorry about that.

I mistakenly put two `updateLocation.schema`s in the `DroneService.js`, **you could do a quick fix by changing the second `updateLocation.schema` to `updateLocationBySerialNumber.schema` (line 269)**. I'm very sorry for the confusing. I hope you won't be stuck in such a mistake in the following challenge.

@kbowerma It's my fault so I will not be the winner of the F2F challenge. Many thanks for choosing my submission as the winning code.

Thank you very much.

**Comment by billsedison** [comment]
Also, I add the PR #174 to fix the bug. I hope it could help you in the following challenges.

Apologies for my mistake again.

Thanks.

**Comment by gondzo** [comment]
fix merged to dev
