### ISSUE TITLE
Can no longer assign drone after accepting package-request

### ISSUE THREAD

**Issue by mtwomey** [topcoderinc/dsp-server#179]
See here: https://youtu.be/7RFWIH-IC7c

The (new) check in services/PackageRequestService.js is throwing this error, it looks like the request is set to 'pending' in an API call just prior to the assign drone call.

**Comment by mtwomey** [comment]
@gondzo Please take a peek in case this was a merge issue.

**Comment by gondzo** [comment]
already fixed, forgot to push to the repo. try now.

**Comment by mtwomey** [comment]
Confirmed - thanks!
